//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOA_TRUCK_WEB_APPLICATION.TruckService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="getCommentPortBinding", Namespace="http://WebServices/")]
    public partial class TruckApplication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getExpenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInnerJoinOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPostalCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInlineViewOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPricingOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMaxTranOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAddressOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerLocationIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTruckOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TruckApplication() {
            this.Url = global::SOA_TRUCK_WEB_APPLICATION.Properties.Settings.Default.SOA_TRUCK_WEB_APPLICATION_TruckService_TruckApplication;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInvoiceCompletedEventHandler getInvoiceCompleted;
        
        /// <remarks/>
        public event getExpenseCompletedEventHandler getExpenseCompleted;
        
        /// <remarks/>
        public event getEmployeeCompletedEventHandler getEmployeeCompleted;
        
        /// <remarks/>
        public event getInnerJoinCompletedEventHandler getInnerJoinCompleted;
        
        /// <remarks/>
        public event getPaymentCompletedEventHandler getPaymentCompleted;
        
        /// <remarks/>
        public event getPriceCompletedEventHandler getPriceCompleted;
        
        /// <remarks/>
        public event getLikeCompletedEventHandler getLikeCompleted;
        
        /// <remarks/>
        public event getCommentCompletedEventHandler getCommentCompleted;
        
        /// <remarks/>
        public event getTransactionCompletedEventHandler getTransactionCompleted;
        
        /// <remarks/>
        public event getCommentDetailsCompletedEventHandler getCommentDetailsCompleted;
        
        /// <remarks/>
        public event getPostalCodeCompletedEventHandler getPostalCodeCompleted;
        
        /// <remarks/>
        public event getCustomerCompletedEventHandler getCustomerCompleted;
        
        /// <remarks/>
        public event getInlineViewCompletedEventHandler getInlineViewCompleted;
        
        /// <remarks/>
        public event getPricingCompletedEventHandler getPricingCompleted;
        
        /// <remarks/>
        public event getCustomerDetailsCompletedEventHandler getCustomerDetailsCompleted;
        
        /// <remarks/>
        public event getMaxTranCompletedEventHandler getMaxTranCompleted;
        
        /// <remarks/>
        public event getAddressCompletedEventHandler getAddressCompleted;
        
        /// <remarks/>
        public event getSubQueryCompletedEventHandler getSubQueryCompleted;
        
        /// <remarks/>
        public event getCustomerLocationIDCompletedEventHandler getCustomerLocationIDCompleted;
        
        /// <remarks/>
        public event getTruckCompletedEventHandler getTruckCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getInvoice() {
            object[] results = this.Invoke("getInvoice", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInvoiceAsync() {
            this.getInvoiceAsync(null);
        }
        
        /// <remarks/>
        public void getInvoiceAsync(object userState) {
            if ((this.getInvoiceOperationCompleted == null)) {
                this.getInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvoiceOperationCompleted);
            }
            this.InvokeAsync("getInvoice", new object[0], this.getInvoiceOperationCompleted, userState);
        }
        
        private void OngetInvoiceOperationCompleted(object arg) {
            if ((this.getInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvoiceCompleted(this, new getInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getExpense() {
            object[] results = this.Invoke("getExpense", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getExpenseAsync() {
            this.getExpenseAsync(null);
        }
        
        /// <remarks/>
        public void getExpenseAsync(object userState) {
            if ((this.getExpenseOperationCompleted == null)) {
                this.getExpenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExpenseOperationCompleted);
            }
            this.InvokeAsync("getExpense", new object[0], this.getExpenseOperationCompleted, userState);
        }
        
        private void OngetExpenseOperationCompleted(object arg) {
            if ((this.getExpenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExpenseCompleted(this, new getExpenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getEmployee() {
            object[] results = this.Invoke("getEmployee", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeAsync() {
            this.getEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void getEmployeeAsync(object userState) {
            if ((this.getEmployeeOperationCompleted == null)) {
                this.getEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeOperationCompleted);
            }
            this.InvokeAsync("getEmployee", new object[0], this.getEmployeeOperationCompleted, userState);
        }
        
        private void OngetEmployeeOperationCompleted(object arg) {
            if ((this.getEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeCompleted(this, new getEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getInnerJoin() {
            object[] results = this.Invoke("getInnerJoin", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInnerJoinAsync() {
            this.getInnerJoinAsync(null);
        }
        
        /// <remarks/>
        public void getInnerJoinAsync(object userState) {
            if ((this.getInnerJoinOperationCompleted == null)) {
                this.getInnerJoinOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInnerJoinOperationCompleted);
            }
            this.InvokeAsync("getInnerJoin", new object[0], this.getInnerJoinOperationCompleted, userState);
        }
        
        private void OngetInnerJoinOperationCompleted(object arg) {
            if ((this.getInnerJoinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInnerJoinCompleted(this, new getInnerJoinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPayment() {
            object[] results = this.Invoke("getPayment", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPaymentAsync() {
            this.getPaymentAsync(null);
        }
        
        /// <remarks/>
        public void getPaymentAsync(object userState) {
            if ((this.getPaymentOperationCompleted == null)) {
                this.getPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPaymentOperationCompleted);
            }
            this.InvokeAsync("getPayment", new object[0], this.getPaymentOperationCompleted, userState);
        }
        
        private void OngetPaymentOperationCompleted(object arg) {
            if ((this.getPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPaymentCompleted(this, new getPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPrice() {
            object[] results = this.Invoke("getPrice", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPriceAsync() {
            this.getPriceAsync(null);
        }
        
        /// <remarks/>
        public void getPriceAsync(object userState) {
            if ((this.getPriceOperationCompleted == null)) {
                this.getPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPriceOperationCompleted);
            }
            this.InvokeAsync("getPrice", new object[0], this.getPriceOperationCompleted, userState);
        }
        
        private void OngetPriceOperationCompleted(object arg) {
            if ((this.getPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPriceCompleted(this, new getPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getLike() {
            object[] results = this.Invoke("getLike", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getLikeAsync() {
            this.getLikeAsync(null);
        }
        
        /// <remarks/>
        public void getLikeAsync(object userState) {
            if ((this.getLikeOperationCompleted == null)) {
                this.getLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLikeOperationCompleted);
            }
            this.InvokeAsync("getLike", new object[0], this.getLikeOperationCompleted, userState);
        }
        
        private void OngetLikeOperationCompleted(object arg) {
            if ((this.getLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLikeCompleted(this, new getLikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getComment() {
            object[] results = this.Invoke("getComment", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCommentAsync() {
            this.getCommentAsync(null);
        }
        
        /// <remarks/>
        public void getCommentAsync(object userState) {
            if ((this.getCommentOperationCompleted == null)) {
                this.getCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommentOperationCompleted);
            }
            this.InvokeAsync("getComment", new object[0], this.getCommentOperationCompleted, userState);
        }
        
        private void OngetCommentOperationCompleted(object arg) {
            if ((this.getCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommentCompleted(this, new getCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getTransaction() {
            object[] results = this.Invoke("getTransaction", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTransactionAsync() {
            this.getTransactionAsync(null);
        }
        
        /// <remarks/>
        public void getTransactionAsync(object userState) {
            if ((this.getTransactionOperationCompleted == null)) {
                this.getTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTransactionOperationCompleted);
            }
            this.InvokeAsync("getTransaction", new object[0], this.getTransactionOperationCompleted, userState);
        }
        
        private void OngetTransactionOperationCompleted(object arg) {
            if ((this.getTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTransactionCompleted(this, new getTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCommentDetails() {
            object[] results = this.Invoke("getCommentDetails", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCommentDetailsAsync() {
            this.getCommentDetailsAsync(null);
        }
        
        /// <remarks/>
        public void getCommentDetailsAsync(object userState) {
            if ((this.getCommentDetailsOperationCompleted == null)) {
                this.getCommentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommentDetailsOperationCompleted);
            }
            this.InvokeAsync("getCommentDetails", new object[0], this.getCommentDetailsOperationCompleted, userState);
        }
        
        private void OngetCommentDetailsOperationCompleted(object arg) {
            if ((this.getCommentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommentDetailsCompleted(this, new getCommentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPostalCode() {
            object[] results = this.Invoke("getPostalCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPostalCodeAsync() {
            this.getPostalCodeAsync(null);
        }
        
        /// <remarks/>
        public void getPostalCodeAsync(object userState) {
            if ((this.getPostalCodeOperationCompleted == null)) {
                this.getPostalCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPostalCodeOperationCompleted);
            }
            this.InvokeAsync("getPostalCode", new object[0], this.getPostalCodeOperationCompleted, userState);
        }
        
        private void OngetPostalCodeOperationCompleted(object arg) {
            if ((this.getPostalCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPostalCodeCompleted(this, new getPostalCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCustomer() {
            object[] results = this.Invoke("getCustomer", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerAsync() {
            this.getCustomerAsync(null);
        }
        
        /// <remarks/>
        public void getCustomerAsync(object userState) {
            if ((this.getCustomerOperationCompleted == null)) {
                this.getCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerOperationCompleted);
            }
            this.InvokeAsync("getCustomer", new object[0], this.getCustomerOperationCompleted, userState);
        }
        
        private void OngetCustomerOperationCompleted(object arg) {
            if ((this.getCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerCompleted(this, new getCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getInlineView() {
            object[] results = this.Invoke("getInlineView", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getInlineViewAsync() {
            this.getInlineViewAsync(null);
        }
        
        /// <remarks/>
        public void getInlineViewAsync(object userState) {
            if ((this.getInlineViewOperationCompleted == null)) {
                this.getInlineViewOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInlineViewOperationCompleted);
            }
            this.InvokeAsync("getInlineView", new object[0], this.getInlineViewOperationCompleted, userState);
        }
        
        private void OngetInlineViewOperationCompleted(object arg) {
            if ((this.getInlineViewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInlineViewCompleted(this, new getInlineViewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPricing() {
            object[] results = this.Invoke("getPricing", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPricingAsync() {
            this.getPricingAsync(null);
        }
        
        /// <remarks/>
        public void getPricingAsync(object userState) {
            if ((this.getPricingOperationCompleted == null)) {
                this.getPricingOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPricingOperationCompleted);
            }
            this.InvokeAsync("getPricing", new object[0], this.getPricingOperationCompleted, userState);
        }
        
        private void OngetPricingOperationCompleted(object arg) {
            if ((this.getPricingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPricingCompleted(this, new getPricingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCustomerDetails() {
            object[] results = this.Invoke("getCustomerDetails", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerDetailsAsync() {
            this.getCustomerDetailsAsync(null);
        }
        
        /// <remarks/>
        public void getCustomerDetailsAsync(object userState) {
            if ((this.getCustomerDetailsOperationCompleted == null)) {
                this.getCustomerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerDetailsOperationCompleted);
            }
            this.InvokeAsync("getCustomerDetails", new object[0], this.getCustomerDetailsOperationCompleted, userState);
        }
        
        private void OngetCustomerDetailsOperationCompleted(object arg) {
            if ((this.getCustomerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerDetailsCompleted(this, new getCustomerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getMaxTran() {
            object[] results = this.Invoke("getMaxTran", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMaxTranAsync() {
            this.getMaxTranAsync(null);
        }
        
        /// <remarks/>
        public void getMaxTranAsync(object userState) {
            if ((this.getMaxTranOperationCompleted == null)) {
                this.getMaxTranOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMaxTranOperationCompleted);
            }
            this.InvokeAsync("getMaxTran", new object[0], this.getMaxTranOperationCompleted, userState);
        }
        
        private void OngetMaxTranOperationCompleted(object arg) {
            if ((this.getMaxTranCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMaxTranCompleted(this, new getMaxTranCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getAddress() {
            object[] results = this.Invoke("getAddress", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getAddressAsync() {
            this.getAddressAsync(null);
        }
        
        /// <remarks/>
        public void getAddressAsync(object userState) {
            if ((this.getAddressOperationCompleted == null)) {
                this.getAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAddressOperationCompleted);
            }
            this.InvokeAsync("getAddress", new object[0], this.getAddressOperationCompleted, userState);
        }
        
        private void OngetAddressOperationCompleted(object arg) {
            if ((this.getAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAddressCompleted(this, new getAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getSubQuery() {
            object[] results = this.Invoke("getSubQuery", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSubQueryAsync() {
            this.getSubQueryAsync(null);
        }
        
        /// <remarks/>
        public void getSubQueryAsync(object userState) {
            if ((this.getSubQueryOperationCompleted == null)) {
                this.getSubQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubQueryOperationCompleted);
            }
            this.InvokeAsync("getSubQuery", new object[0], this.getSubQueryOperationCompleted, userState);
        }
        
        private void OngetSubQueryOperationCompleted(object arg) {
            if ((this.getSubQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubQueryCompleted(this, new getSubQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCustomerLocationID() {
            object[] results = this.Invoke("getCustomerLocationID", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerLocationIDAsync() {
            this.getCustomerLocationIDAsync(null);
        }
        
        /// <remarks/>
        public void getCustomerLocationIDAsync(object userState) {
            if ((this.getCustomerLocationIDOperationCompleted == null)) {
                this.getCustomerLocationIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerLocationIDOperationCompleted);
            }
            this.InvokeAsync("getCustomerLocationID", new object[0], this.getCustomerLocationIDOperationCompleted, userState);
        }
        
        private void OngetCustomerLocationIDOperationCompleted(object arg) {
            if ((this.getCustomerLocationIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerLocationIDCompleted(this, new getCustomerLocationIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://WebServices/", ResponseNamespace="http://WebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getTruck() {
            object[] results = this.Invoke("getTruck", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTruckAsync() {
            this.getTruckAsync(null);
        }
        
        /// <remarks/>
        public void getTruckAsync(object userState) {
            if ((this.getTruckOperationCompleted == null)) {
                this.getTruckOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTruckOperationCompleted);
            }
            this.InvokeAsync("getTruck", new object[0], this.getTruckOperationCompleted, userState);
        }
        
        private void OngetTruckOperationCompleted(object arg) {
            if ((this.getTruckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTruckCompleted(this, new getTruckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getInvoiceCompletedEventHandler(object sender, getInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getExpenseCompletedEventHandler(object sender, getExpenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExpenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExpenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getEmployeeCompletedEventHandler(object sender, getEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getInnerJoinCompletedEventHandler(object sender, getInnerJoinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInnerJoinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInnerJoinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getPaymentCompletedEventHandler(object sender, getPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getPriceCompletedEventHandler(object sender, getPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getLikeCompletedEventHandler(object sender, getLikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCommentCompletedEventHandler(object sender, getCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getTransactionCompletedEventHandler(object sender, getTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCommentDetailsCompletedEventHandler(object sender, getCommentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getPostalCodeCompletedEventHandler(object sender, getPostalCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPostalCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPostalCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCustomerCompletedEventHandler(object sender, getCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getInlineViewCompletedEventHandler(object sender, getInlineViewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInlineViewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInlineViewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getPricingCompletedEventHandler(object sender, getPricingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPricingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPricingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCustomerDetailsCompletedEventHandler(object sender, getCustomerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getMaxTranCompletedEventHandler(object sender, getMaxTranCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMaxTranCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMaxTranCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getAddressCompletedEventHandler(object sender, getAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getSubQueryCompletedEventHandler(object sender, getSubQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getCustomerLocationIDCompletedEventHandler(object sender, getCustomerLocationIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerLocationIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerLocationIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getTruckCompletedEventHandler(object sender, getTruckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTruckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTruckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591